### ISSUE TITLE
Computer has no copy assignment operator

### ISSUE THREAD

**Issue by maxhwardg** [Edgeworth/memerna#15]
‘mrna::Computed& mrna::Computed::operator=(const mrna::Computed&)’ is implicitly declared as deleted because ‘mrna::Computed’ declares a move constructor or move assignment operator

**Comment by Edgeworth** [comment]
In general, the large structures have copy disabled to make it less likely to make performance mistakes. The only reason this isn't the case for primary and secondary is because I haven't made special types for them yet. If you want to copy you can explicitly use the constructor. If there isn't one feel free to add one (an explicit copy constructor).

If you can get away with moves that's better imo.

How often do you need to copy? What does the code look like?

**Comment by Edgeworth** [comment]
Computed type is gone now. In general, if you want to copy, use one of the explicit copy constructors.
