### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by turix2** [Edgeworth/memerna#28]
I'm trying to build memerna for the first time and have run into several C++ errors.

The command line I used to build (within a poetry shell) was:
```python3.11 -m rnapy.run build --regenerate --compiler gcc  --memerna-src-path . --prefix ./bin memerna```

... where `gcc` is mapped to `gcc-10` version `10.3.0`, installed (roughly) from the instructions [here](https://gasparri.org/2020/07/30/installing-c17-and-c20-on-ubuntu-and-amazon-linux/).

I am attaching a file with the output:  [build_out.txt](https://github.com/Edgeworth/memerna/files/12188620/build_out.txt)

More details about my system (which is more or less "up-to-date"):
```
$ uname -srm
Linux 4.15.0-210-generic x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Please let me know should you need any more info.
Thanks!

**Comment by Edgeworth** [comment]
Thanks for the report.

Since memerna uses very recent C++ features, it needs a recent toolchain, like gcc-12 or clang-15.

We should:
1. Document required toolchain versions
2. Check library versions (and optionally download if missing via e.g. https://github.com/cpm-cmake/CPM.cmake)
3. (stretch) Set up CI to verify build and tests using minimum required toolchain versions. Currently this is done locally using ./check.sh but it uses the system toolchain.

**Comment by Edgeworth** [comment]
1 and 2 above are done. Going to close this
